Fix multicluster labels
kubernetes-monitoring/kubernetes-mixin pull request #754
Opened 2022-03-22 20:38 UTC by phillebaba

More fixes like #752 for multi cluster labels which can cause issues if labels overlap.

2022-03-23 10:03 UTC, arajkumar commented
@phillebaba Tests are failing, please fix it.

2022-03-23 10:07 UTC, arajkumar requested changes

2022-03-23 10:07 UTC, arajkumar commented on alerts/system_alerts.libsonnet
>              |||,
```suggestion
            ||| % $._config,
```

2022-03-23 10:11 UTC, arajkumar requested changes

2022-03-23 10:11 UTC, arajkumar commented on alerts/kubelet.libsonnet
>                  (kube_pod_status_phase{%(kubeStateMetricsSelector)s,phase="Running"} == 1) * on(instance,pod,namespace,cluster) group_left(node) topk by(instance,pod,namespace,cluster) (1, kube_pod_i
```suggestion
                (kube_pod_status_phase{%(kubeStateMetricsSelector)s,phase="Running"} == 1) * on(instance,pod,namespace,%(clusterLabel)s) group_left(node) topk by(instance,pod,namespace,%(clusterLabel)s) (1, kube_pod_info{%(kubeStateMetricsSelector)s})
```

2022-03-29 15:58 UTC, phillebaba commented
@arajkumar thanks for the help, should be all set now!

2022-03-30 09:09 UTC, metalmatze approved these changes

2022-03-30 09:09 UTC, metalmatze commented
Thanks!

2022-03-30 09:09 UTC, merged